import PropTypes from 'prop-types'
import { css } from 'glamor'
import cx from 'classnames'

export const propTypes = {
  border: PropTypes.string,
  borderColor: PropTypes.string,
  borderStyle: PropTypes.string,
  borderWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  borderLeft: PropTypes.string,
  borderLeftColor: PropTypes.string,
  borderLeftStyle: PropTypes.string,
  borderLeftWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  borderRight: PropTypes.string,
  borderRightColor: PropTypes.string,
  borderRightStyle: PropTypes.string,
  borderRightWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  borderTop: PropTypes.string,
  borderTopColor: PropTypes.string,
  borderTopStyle: PropTypes.string,
  borderTopWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
  borderBottom: PropTypes.string,
  borderBottomColor: PropTypes.string,
  borderBottomStyle: PropTypes.string,
  borderBottomWidth: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
}

export const parseProps = ({
  border,
  borderColor,
  borderStyle,
  borderWidth,
  borderLeft,
  borderLeftColor,
  borderLeftStyle,
  borderLeftWidth,
  borderRight,
  borderRightColor,
  borderRightStyle,
  borderRightWidth,
  borderTop,
  borderTopColor,
  borderTopStyle,
  borderTopWidth,
  borderBottom,
  borderBottomColor,
  borderBottomStyle,
  borderBottomWidth,
  className,
  ...props
}) => ({
  ...props,
  className: cx(
    className,
    border !== undefined && css({ border }).toString(),
    borderColor !== undefined && css({ borderColor }).toString(),
    borderStyle !== undefined && css({ borderStyle }).toString(),
    borderWidth !== undefined && css({ borderWidth }).toString(),
    borderLeft !== undefined && css({ borderLeft }).toString(),
    borderLeftColor !== undefined && css({ borderLeftColor }).toString(),
    borderLeftStyle !== undefined && css({ borderLeftStyle }).toString(),
    borderLeftWidth !== undefined && css({ borderLeftWidth }).toString(),
    borderRight !== undefined && css({ borderRight }).toString(),
    borderRightColor !== undefined && css({ borderRightColor }).toString(),
    borderRightStyle !== undefined && css({ borderRightStyle }).toString(),
    borderRightWidth !== undefined && css({ borderRightWidth }).toString(),
    borderTop !== undefined && css({ borderTop }).toString(),
    borderTopColor !== undefined && css({ borderTopColor }).toString(),
    borderTopStyle !== undefined && css({ borderTopStyle }).toString(),
    borderTopWidth !== undefined && css({ borderTopWidth }).toString(),
    borderBottom !== undefined && css({ borderBottom }).toString(),
    borderBottomColor !== undefined && css({ borderBottomColor }).toString(),
    borderBottomStyle !== undefined && css({ borderBottomStyle }).toString(),
    borderBottomWidth !== undefined && css({ borderBottomWidth }).toString()
  ),
})
